% Base de dados de filmes

filme("Inception","Thriller",2010,148,"United States, Great Britain","Christopher Nolan",["Joseph Gordon-Levitt", "Leonardo DiCaprio", "Ellen Page", "Marion Cotillard", "Cillian Murphy", "Michael Caine", "Tom Hardy", "Tom Berenger", "Lukas Haas", "Ken Watanabe"]).
filme("Kanata no uta","Drama",2023,84,"Japan","Kyoshi Sugita",["An Ogawa", "Yûko Nakamura", "Hidekazu Mashima"]).
filme("Los océanos son los verdaderos continentes","Documentary",2023,119,"Italy, Cuba","Tommaso Santambrogio",["Alexander Diego", "Edith Ybarra Clara", "Frank Ernesto Lam", "Alain Alfonso González", "Milagros Llanes Martínez"]).
filme("Vampire humaniste cherche suicidaire consentant","Comedy",2023,92,"Canada","Ariane Louis-Seize",["Sara Montpetit", "Félix-Antoine Bénard", "Steve Laplante", "Sophie Cadieux", "Noémie OFarrell", "Lilas-Rose Cantin", "Arnaud Vachon", "Marie Brassard", "Madeleine Péloquin", "Gabriel-Antoine Roy", "Isabella Villalba", "Patrick Hivon", "Marc Beaupré", "Micheline Bernard", "Sylvie Lemay", "Ariane Castellanos"]).
filme("Wu yue xue","History",2023,116,"Malaysia, Singapore, China","Keat Aun Chong",["Fang Wan", "Pearlly Chua", "Jen-Shuo Cheng", "Pauline Tan", "Peter Yu", "Alvin Wong", "Wei Hern Teoh", "Koet Yenn Lim", "Zi Ting Lee", "Kok Hin Kuan"]).
filme("Pool Boy Nightmare","Thriller",2020,86,"United States","Rolfe Kanefsky",["Jessica Morris", "Tanner Zagarino", "Ellie Darcey-Alden", "Cynthia Aileen Strahan", "Clark Moore", "Valeria Gómez", "Luis Fernandez-Gil", "Angela Nicholas", "Charlie Townsend", "Gina Hiraizumi", "Sarah French", "Mario Garcia", "Ben Stobber"]).
filme("Shelter","Thriller",2023,91,"United States","Anthony Nardolillo",["Cam Gigandet", "Jaina Lee Ortiz", "Lisa Vidal", "Carlos Miranda", "Michael Fairman", "Paul Kreppel", "Danube Hermosillo", "Brian Cousins", "Jason Scott Jenkins", "James Crittenden", "Tiago Roberts", "Benjamin Schnau", "Mitch Poulos", "Melissa Marty", "Sasha Merci", "Katee Shean", "Alfred Hsing", "David Gilchrist"]).
filme("Sentinelle","Action",2023,99,"France",["Hugo Benamozig", "David Caviglioli"],["Jonathan Cohen", "Emmanuelle Bercot", "Raphaël Quenard", "Gustave Kervern", "Ramzy Bedia"]).
filme("Killer Prom","Thriller",2020,85,"Canada","Alexandre Carrière",["Yvonne Zima", "Mark Lutz", "Erica Anderson", "John Andrews", "Jasmine Asha", "Brianna Barnes", "L. Fernando Becerra Sánchez", "Manny Benda", "Jordan Blais", "Gabriel Darku", "May Dib", "Lorilee Holloway", "Madelyn Keys", "Ronda Louis-Jeune", "Kyle Meagher", "Heather Tod Mitchell", "Megan Vincent", "Dan Day"]).
filme("El club de los lectores criminales","Horror",2023,89,"Spain","Carlos Alonso Ojea",["Veki Velilla", "Iván Pellicer", "Álvaro Mel", "Daniel Grao", "Priscilla Delgado", "Iván López", "Carlos Alcaide", "María Cerezuela", "Ane Rot", "Carmela Lloret", "Hamza Zaidi"]).
filme("En dag och en halv","Thriller",2023,94,"Sweden","Fares Fares",["Fares Fares", "Alexej Manvelov", "Alma Pöysti", "Stina Ekblad", "Annika Hallin", "Richard Forsgren", "Annica Liljeblad", "Johni Tadi", "Jonathan Sand", "Bengt C.W. Carlsson", "Amicia Heijbel", "Bella Klaus", "Clara Hallencreutz Fares", "Karl Larsson", "Lisa Forslund", "Linda Hellström", "Nils Westman", "Bengt Malmgren"]).
filme("To End All War: Oppenheimer & the Atomic Bomb","Documentary",2023,87,"United States","Christopher Cassel",["J. Robert Oppenheimer", "Kai Bird", "Ellen Bradbury", "Alan B. Carr", "Jennet Conant", "Albert Einstein", "David Eisenbach", "Jon Else", "Leslie Groves", "Gregg Herken", "Adolf Hitler", "Michio Kaku", "Joseph McCarthy", "Christopher Nolan", "Bill Nye", "Charles Oppenheimer", "Richard Rhodes", "Eleanor Roosevelt"]).
filme("Schon Tausendmal Berührt","Romantic",2022,88,"Germany","Judith Westermann",["Zeynep Bozbay", "Heinz-Josef Braun", "Inez Bjørg David", "Agnes Kiyomi Decker", "Ursula Karven", "Marie Nasemann", "Leo Reisinger", "Roland Schreglmann", "Elena Uhlig", "Benedikt Zimmermann", "Stephan Zinner"]).
filme("Hostage House","Horror",2021,85,"United States","David Benullo",["Jennifer Taylor", "Justin C. Schilling", "Julia Terranova", "Emily Sweet", "Patrick Cronen", "Jasmine Newell", "Richard Neil", "Kamen Casey", "Sabreena Iman", "Danielle Yoshiko Phillips", "Bryce Barfield", "Katy Hayes", "Tristan Hutchison", "Michelle Sander", "Mark White", "Kevin Yap"]).
filme("Fear the Night","Horror",2023,92,"United States","Neil LaBute",["Maggie Q", "Ito Aghayere", "Philip Burke", "James Carpinello", "Christopher Corbin", "Gia Crovatin", "Kat Foster", "Treisa Gary", "Travis Hammer", "KeiLyn Durrel Jones", "Highdee Kuan", "Kirstin Leigh", "Brenda Meaney", "Jack Mikesell", "Ray Nicholson", "Geoff Pierson", "William Roth", "Roshni Shukla"]).
filme("American Moon","Documentary",2017,214,"Italy","Massimo Mazzucco",["Paolo Attivissimo", "Aldo Fallai", "Peter Lindbergh", "Danilo Pasqua", "Nicola Pecorini", "Clive Riche", "Christophe Terrasson", "Toni Thorimbert", "Oliviero Toscani", "Daniele Vanoni"]).
filme("Znachor","Romantic",2023,140,"Poland","Michal Gazda",["Leszek Lichota", "Maria Kowalska", "Ignacy Liss", "Anna Szymanczyk", "Malgorzata Mikolajczak", "Izabela Kuna", "Pawel Tomaszewski", "Miroslaw Haniszewski", "Mikolaj Grabowski", "Lukasz Szczepanowski"]).
filme("Love Is in the Air","Romantic",2023,88,"Australia","Adrian Powers",["Delta Goodrem", "Joshua Sasse", "Roy Billing", "Steph Tisdell", "Simon Brook McLachlan", "Daniela Pizzirani", "Mia Grunwald", "Hugh Parker", "Dante Surace"]).
filme("Nowhere","Thriller",2023,109,"Spain","Albert Pintó",["Anna Castillo", "Tamar Novas"]).
filme("Mes petites amoureuses","Drama",1974,123,"France","Jean Eustache",["Martin Loeb", "Jacqueline Dufranne", "Jacques Romain", "Ingrid Caven", "Vincent Testanière", "Roger Rizzi", "Anne Stroka", "Cirque Muller", "Syndra Kahn", "Jean-Jacques Bihan", "Ghislaine Lakomy", "Brigitte Pangaud", "Michele Deboutet", "Dionys Mascolo", "Claire Treille", "Louis Caut", "Patrick Eustache", "Henri Martinez"]).
filme("Organ Trail","Western",2023,112,"United States","Michael Patrick Jann",["Zoé De Grand Maison", "Mather Zickel", "Lisa LoCicero", "Lukas Jann", "Olivia Grace Applegate", "Sam Trammell", "Nicholas Logan", "Michael Abbott Jr.", "Alejandro Akara", "Clé Bennett", "Jessica Frances Dukes", "Thomas Lennon"]).
filme("Hidden Family Secrets","Thriller",2021,87,"Canada","Stefan Brogren",["Alex Paxton-Beesley", "Madelyn Keys", "Sonja Smits", "Nck Name", "Gabriel Venneri", "Zoe Sarantakis", "Christian Paul", "Louise Kerr", "Gracie Callahan", "Jimmy Chimarios", "Fallon Bowman", "Geraldine Ronan", "Emmerly Tinglin", "Holly Jade Balmer", "Alexandre Cadieux"]).
filme("La stoccata vincente","Biography",2023,107,"Italy","Nicola Campiotti",["Alessio Vassallo", "Flavio Insinna", "Elena Funari", "Chiara Cavaliere", "Mario Ermito", "Samuele Carrino", "Carlotta Ventimiglia", "Svetlana Kevral", "Egle Doria", "Maciej Robakiewicz"]).
filme("Gold Digger Killer","Thriller",2021,87,"Canada, United States","Robin Hays",["Julie Benz", "Roan Curtis", "Georgia Bradner", "Eli Gabay", "Justine Warrington", "Rob LaBelle", "Viv Leacock", "Laara Sadiq", "Patricia Harras", "Anthony Timpano", "Karen Holness", "Beverley Elliott", "Wonita Joy", "Nicole Anthony", "Ardy Ramezani", "Zahra Alani", "Tanya Jade", "Malaika Jackson"]).
filme("Addio al nubilato 2","Comedy",2023,90,"Italy","Francesco Apolloni",["Laura Chiatti", "Chiara Francini", "Antonia Liskova", "Jun Ichikawa", "Enula", "Fabrizio Nardi", "Giovanni James Bertoia", "Radu Murarasu"]).
filme("Konferensen","Horror",2023,100,"Sweden","Patrik Eklund",["Katia Winter", "Eva Melander", "Lola Zackow", "Adam Lundgren", "Margareta Pettersson", "Cecilia Nilsson", "Christoffer Nordenrot", "Maria Sid", "Amed Bozan", "Jimmy Lindström", "Robert Follin", "Claes Hartelius", "Marie Agerhäll", "Martin Lagos"]).
filme("Ballelina","Thriller",2023,92,"South Korea","Chung-Hyun Lee",["Jeon Jong-seo", "Park Yu-rim", "Ji-hun Kim"]).
filme("Invitación a un Asesinato","Thriller",2023,92,"Mexico","J.M Cravioto",["Maribel Verdú", "Stephanie Cayo", "Manolo Cardona", "Aarón Díaz", "Regina Blandón", "José María de Tavira", "Frank Maldonado"]).
